Name_of_Student=input("Enter your full name")
Name_of_Father= input("Enter the name of your father")
Roll_Number= input("Please enter your roll number")
course_Name= input("Please enter your course name")
Subject_1 = int(input("Please Enter the marks of Subject 1"))
Subject_2 = int(input("Please Enter the marks of Subject 2"))
Subject_3 = int(input("Please Enter the marks of Subject 3"))
Subject_4 = int(input("Please Enter the marks of Subject 4"))
Subject_5 = int(input("Please Enter the marks of Subject 5"))
Grand_Total=Subject_1+Subject_2+Subject_3+Subject_4+Subject_5
string="Acropolis Institute of Technology & Research, Indore"
print("|" + "-" *78 + "|")
print ("|" + string.center(78) + "|")
print("|" +course_Name.center(78) + "|")
print("|" + "-" *78 + "|")
print("|" + "Name of Student:" + Name_of_Student.ljust(62) +"|") 
print("|" + "Name of Student:" + Name_of_Father.ljust(62) +"|")  
print("|" + "Name of Student:" + Roll_Number.ljust(62) +"|")  
print("|" + "-" *78 + "|")
print("|{:^28}|{:^23}|{:^13}|{:^10}|".format("Subject", "Maximum Marks", "Marks Obtained", "Total"))
print("|" + "-" *78 + "|")
print("|"+ "Mathematics-III"+" "*13 + "|"+ "{:^23}".format("100")+ "|"+ "{:^14}".format(Subject_1)+ "|"+ "{:^10}".format(Subject_1)+ "|")
print("|"+ "Data Structure"+" "*14 + "|"+ "{:^23}".format("100")+ "|"+ "{:^14}".format(Subject_2)+ "|"+ "{:^10}".format(Subject_2)+ "|")
print("|"+ "EDC"+" "*25 + "|"+ "{:^23}".format("100")+ "|"+ "{:^14}".format(Subject_3)+ "|"+ "{:^10}".format(Subject_3)+ "|")
print("|"+ "DCS"+" "*25 + "|"+ "{:^23}".format("100")+ "|"+ "{:^14}".format(Subject_4)+ "|"+ "{:^10}".format(Subject_4)+ "|")
print("|"+ "OOT"+" "*25 + "|"+ "{:^23}".format("100")+ "|"+ "{:^14}".format(Subject_5)+ "|"+ "{:^10}".format(Subject_5)+ "|")
print("|"+" " *28 + "|" + " "*23 + "|" + " " *14 + "|"+" "*10 +"|")
print("|"+" " *28 + "|" + " "*23 + "|" + " " *14 + "|"+" "*10 +"|") 
print("|"+" " *28 + "|" + " "*23 + "|" + " " *14 + "|"+" "*10 +"|")
print("|"+" " *28 + "|" + " "*23 + "|" + " " *14 + "|"+" "*10 +"|")
print("|"+" " *28 + "|" + " "*23 + "|" + " " *14 + "|"+" "*10 +"|")
print("|"+" " *28 + "|" + " "*23 + "|" + " " *14 + "|"+" "*10 +"|")
print("|" + "-" *78 + "|")
print(" " *56 +"|"+ "Grand Total"+"|", Grand_Total, " "*5+ "|")
print(" " *56 +"|"+ "-"*22+"|")
print("\n\n\n\n\n")
print("Deepak Agrawal".rjust(80))
print("Chancelor".rjust(78))

